#include <json.h>

namespace {

#define LUMALINK_JSON_FIELD_DECL(N) int field_##N;
#define LUMALINK_JSON_FIELD_SPEC(N) lumalink::json::spec::field<"field_" #N, lumalink::json::spec::integer<>>

#define LUMALINK_JSON_FIELD_DECL_BLOCK_00 \
    LUMALINK_JSON_FIELD_DECL(0) \
    LUMALINK_JSON_FIELD_DECL(1) \
    LUMALINK_JSON_FIELD_DECL(2) \
    LUMALINK_JSON_FIELD_DECL(3) \
    LUMALINK_JSON_FIELD_DECL(4) \
    LUMALINK_JSON_FIELD_DECL(5) \
    LUMALINK_JSON_FIELD_DECL(6) \
    LUMALINK_JSON_FIELD_DECL(7) \
    LUMALINK_JSON_FIELD_DECL(8) \
    LUMALINK_JSON_FIELD_DECL(9)

#define LUMALINK_JSON_FIELD_DECL_BLOCK_01 \
    LUMALINK_JSON_FIELD_DECL(10) \
    LUMALINK_JSON_FIELD_DECL(11) \
    LUMALINK_JSON_FIELD_DECL(12) \
    LUMALINK_JSON_FIELD_DECL(13) \
    LUMALINK_JSON_FIELD_DECL(14) \
    LUMALINK_JSON_FIELD_DECL(15) \
    LUMALINK_JSON_FIELD_DECL(16) \
    LUMALINK_JSON_FIELD_DECL(17) \
    LUMALINK_JSON_FIELD_DECL(18) \
    LUMALINK_JSON_FIELD_DECL(19)

#define LUMALINK_JSON_FIELD_DECL_BLOCK_02 \
    LUMALINK_JSON_FIELD_DECL(20) \
    LUMALINK_JSON_FIELD_DECL(21) \
    LUMALINK_JSON_FIELD_DECL(22) \
    LUMALINK_JSON_FIELD_DECL(23) \
    LUMALINK_JSON_FIELD_DECL(24) \
    LUMALINK_JSON_FIELD_DECL(25) \
    LUMALINK_JSON_FIELD_DECL(26) \
    LUMALINK_JSON_FIELD_DECL(27) \
    LUMALINK_JSON_FIELD_DECL(28) \
    LUMALINK_JSON_FIELD_DECL(29)

#define LUMALINK_JSON_FIELD_DECL_BLOCK_03 \
    LUMALINK_JSON_FIELD_DECL(30) \
    LUMALINK_JSON_FIELD_DECL(31) \
    LUMALINK_JSON_FIELD_DECL(32) \
    LUMALINK_JSON_FIELD_DECL(33) \
    LUMALINK_JSON_FIELD_DECL(34) \
    LUMALINK_JSON_FIELD_DECL(35) \
    LUMALINK_JSON_FIELD_DECL(36) \
    LUMALINK_JSON_FIELD_DECL(37) \
    LUMALINK_JSON_FIELD_DECL(38) \
    LUMALINK_JSON_FIELD_DECL(39)

#define LUMALINK_JSON_FIELD_DECL_BLOCK_04 \
    LUMALINK_JSON_FIELD_DECL(40) \
    LUMALINK_JSON_FIELD_DECL(41) \
    LUMALINK_JSON_FIELD_DECL(42) \
    LUMALINK_JSON_FIELD_DECL(43) \
    LUMALINK_JSON_FIELD_DECL(44) \
    LUMALINK_JSON_FIELD_DECL(45) \
    LUMALINK_JSON_FIELD_DECL(46) \
    LUMALINK_JSON_FIELD_DECL(47) \
    LUMALINK_JSON_FIELD_DECL(48) \
    LUMALINK_JSON_FIELD_DECL(49)

#define LUMALINK_JSON_FIELD_DECL_BLOCK_05 \
    LUMALINK_JSON_FIELD_DECL(50) \
    LUMALINK_JSON_FIELD_DECL(51) \
    LUMALINK_JSON_FIELD_DECL(52) \
    LUMALINK_JSON_FIELD_DECL(53) \
    LUMALINK_JSON_FIELD_DECL(54) \
    LUMALINK_JSON_FIELD_DECL(55) \
    LUMALINK_JSON_FIELD_DECL(56) \
    LUMALINK_JSON_FIELD_DECL(57) \
    LUMALINK_JSON_FIELD_DECL(58) \
    LUMALINK_JSON_FIELD_DECL(59)

#define LUMALINK_JSON_FIELD_DECL_BLOCK_06 \
    LUMALINK_JSON_FIELD_DECL(60) \
    LUMALINK_JSON_FIELD_DECL(61) \
    LUMALINK_JSON_FIELD_DECL(62) \
    LUMALINK_JSON_FIELD_DECL(63) \
    LUMALINK_JSON_FIELD_DECL(64) \
    LUMALINK_JSON_FIELD_DECL(65) \
    LUMALINK_JSON_FIELD_DECL(66) \
    LUMALINK_JSON_FIELD_DECL(67) \
    LUMALINK_JSON_FIELD_DECL(68) \
    LUMALINK_JSON_FIELD_DECL(69)

#define LUMALINK_JSON_FIELD_DECL_BLOCK_07 \
    LUMALINK_JSON_FIELD_DECL(70) \
    LUMALINK_JSON_FIELD_DECL(71) \
    LUMALINK_JSON_FIELD_DECL(72) \
    LUMALINK_JSON_FIELD_DECL(73) \
    LUMALINK_JSON_FIELD_DECL(74) \
    LUMALINK_JSON_FIELD_DECL(75) \
    LUMALINK_JSON_FIELD_DECL(76) \
    LUMALINK_JSON_FIELD_DECL(77) \
    LUMALINK_JSON_FIELD_DECL(78) \
    LUMALINK_JSON_FIELD_DECL(79)

#define LUMALINK_JSON_FIELD_DECL_BLOCK_08 \
    LUMALINK_JSON_FIELD_DECL(80) \
    LUMALINK_JSON_FIELD_DECL(81) \
    LUMALINK_JSON_FIELD_DECL(82) \
    LUMALINK_JSON_FIELD_DECL(83) \
    LUMALINK_JSON_FIELD_DECL(84) \
    LUMALINK_JSON_FIELD_DECL(85) \
    LUMALINK_JSON_FIELD_DECL(86) \
    LUMALINK_JSON_FIELD_DECL(87) \
    LUMALINK_JSON_FIELD_DECL(88) \
    LUMALINK_JSON_FIELD_DECL(89)

#define LUMALINK_JSON_FIELD_DECL_BLOCK_09 \
    LUMALINK_JSON_FIELD_DECL(90) \
    LUMALINK_JSON_FIELD_DECL(91) \
    LUMALINK_JSON_FIELD_DECL(92) \
    LUMALINK_JSON_FIELD_DECL(93) \
    LUMALINK_JSON_FIELD_DECL(94) \
    LUMALINK_JSON_FIELD_DECL(95) \
    LUMALINK_JSON_FIELD_DECL(96) \
    LUMALINK_JSON_FIELD_DECL(97) \
    LUMALINK_JSON_FIELD_DECL(98) \
    LUMALINK_JSON_FIELD_DECL(99)

#define LUMALINK_JSON_FIELD_DECL_BLOCK_10 \
    LUMALINK_JSON_FIELD_DECL(100) \
    LUMALINK_JSON_FIELD_DECL(101) \
    LUMALINK_JSON_FIELD_DECL(102) \
    LUMALINK_JSON_FIELD_DECL(103) \
    LUMALINK_JSON_FIELD_DECL(104) \
    LUMALINK_JSON_FIELD_DECL(105) \
    LUMALINK_JSON_FIELD_DECL(106) \
    LUMALINK_JSON_FIELD_DECL(107) \
    LUMALINK_JSON_FIELD_DECL(108) \
    LUMALINK_JSON_FIELD_DECL(109)

#define LUMALINK_JSON_FIELD_DECL_BLOCK_11 \
    LUMALINK_JSON_FIELD_DECL(110) \
    LUMALINK_JSON_FIELD_DECL(111) \
    LUMALINK_JSON_FIELD_DECL(112) \
    LUMALINK_JSON_FIELD_DECL(113) \
    LUMALINK_JSON_FIELD_DECL(114) \
    LUMALINK_JSON_FIELD_DECL(115) \
    LUMALINK_JSON_FIELD_DECL(116) \
    LUMALINK_JSON_FIELD_DECL(117) \
    LUMALINK_JSON_FIELD_DECL(118) \
    LUMALINK_JSON_FIELD_DECL(119)

#define LUMALINK_JSON_FIELD_DECL_BLOCK_12 \
    LUMALINK_JSON_FIELD_DECL(120) \
    LUMALINK_JSON_FIELD_DECL(121) \
    LUMALINK_JSON_FIELD_DECL(122) \
    LUMALINK_JSON_FIELD_DECL(123) \
    LUMALINK_JSON_FIELD_DECL(124) \
    LUMALINK_JSON_FIELD_DECL(125) \
    LUMALINK_JSON_FIELD_DECL(126) \
    LUMALINK_JSON_FIELD_DECL(127) \
    LUMALINK_JSON_FIELD_DECL(128) \
    LUMALINK_JSON_FIELD_DECL(129)

#define LUMALINK_JSON_FIELD_DECL_BLOCK_13 \
    LUMALINK_JSON_FIELD_DECL(130) \
    LUMALINK_JSON_FIELD_DECL(131) \
    LUMALINK_JSON_FIELD_DECL(132) \
    LUMALINK_JSON_FIELD_DECL(133) \
    LUMALINK_JSON_FIELD_DECL(134) \
    LUMALINK_JSON_FIELD_DECL(135) \
    LUMALINK_JSON_FIELD_DECL(136) \
    LUMALINK_JSON_FIELD_DECL(137) \
    LUMALINK_JSON_FIELD_DECL(138) \
    LUMALINK_JSON_FIELD_DECL(139)

#define LUMALINK_JSON_FIELD_DECL_BLOCK_14 \
    LUMALINK_JSON_FIELD_DECL(140) \
    LUMALINK_JSON_FIELD_DECL(141) \
    LUMALINK_JSON_FIELD_DECL(142) \
    LUMALINK_JSON_FIELD_DECL(143) \
    LUMALINK_JSON_FIELD_DECL(144) \
    LUMALINK_JSON_FIELD_DECL(145) \
    LUMALINK_JSON_FIELD_DECL(146) \
    LUMALINK_JSON_FIELD_DECL(147) \
    LUMALINK_JSON_FIELD_DECL(148) \
    LUMALINK_JSON_FIELD_DECL(149)

#define LUMALINK_JSON_FIELD_DECL_BLOCK_15 \
    LUMALINK_JSON_FIELD_DECL(150) \
    LUMALINK_JSON_FIELD_DECL(151) \
    LUMALINK_JSON_FIELD_DECL(152) \
    LUMALINK_JSON_FIELD_DECL(153) \
    LUMALINK_JSON_FIELD_DECL(154) \
    LUMALINK_JSON_FIELD_DECL(155) \
    LUMALINK_JSON_FIELD_DECL(156) \
    LUMALINK_JSON_FIELD_DECL(157) \
    LUMALINK_JSON_FIELD_DECL(158) \
    LUMALINK_JSON_FIELD_DECL(159)

#define LUMALINK_JSON_FIELD_DECL_BLOCK_16 \
    LUMALINK_JSON_FIELD_DECL(160) \
    LUMALINK_JSON_FIELD_DECL(161) \
    LUMALINK_JSON_FIELD_DECL(162) \
    LUMALINK_JSON_FIELD_DECL(163) \
    LUMALINK_JSON_FIELD_DECL(164) \
    LUMALINK_JSON_FIELD_DECL(165) \
    LUMALINK_JSON_FIELD_DECL(166) \
    LUMALINK_JSON_FIELD_DECL(167) \
    LUMALINK_JSON_FIELD_DECL(168) \
    LUMALINK_JSON_FIELD_DECL(169)

#define LUMALINK_JSON_FIELD_DECL_BLOCK_17 \
    LUMALINK_JSON_FIELD_DECL(170) \
    LUMALINK_JSON_FIELD_DECL(171) \
    LUMALINK_JSON_FIELD_DECL(172) \
    LUMALINK_JSON_FIELD_DECL(173) \
    LUMALINK_JSON_FIELD_DECL(174) \
    LUMALINK_JSON_FIELD_DECL(175) \
    LUMALINK_JSON_FIELD_DECL(176) \
    LUMALINK_JSON_FIELD_DECL(177) \
    LUMALINK_JSON_FIELD_DECL(178) \
    LUMALINK_JSON_FIELD_DECL(179)

#define LUMALINK_JSON_FIELD_DECL_BLOCK_18 \
    LUMALINK_JSON_FIELD_DECL(180) \
    LUMALINK_JSON_FIELD_DECL(181) \
    LUMALINK_JSON_FIELD_DECL(182) \
    LUMALINK_JSON_FIELD_DECL(183) \
    LUMALINK_JSON_FIELD_DECL(184) \
    LUMALINK_JSON_FIELD_DECL(185) \
    LUMALINK_JSON_FIELD_DECL(186) \
    LUMALINK_JSON_FIELD_DECL(187) \
    LUMALINK_JSON_FIELD_DECL(188) \
    LUMALINK_JSON_FIELD_DECL(189)

#define LUMALINK_JSON_FIELD_DECL_BLOCK_19 \
    LUMALINK_JSON_FIELD_DECL(190) \
    LUMALINK_JSON_FIELD_DECL(191) \
    LUMALINK_JSON_FIELD_DECL(192) \
    LUMALINK_JSON_FIELD_DECL(193) \
    LUMALINK_JSON_FIELD_DECL(194) \
    LUMALINK_JSON_FIELD_DECL(195) \
    LUMALINK_JSON_FIELD_DECL(196) \
    LUMALINK_JSON_FIELD_DECL(197) \
    LUMALINK_JSON_FIELD_DECL(198) \
    LUMALINK_JSON_FIELD_DECL(199)

#define LUMALINK_JSON_FIELD_DECL_BLOCK_20 \
    LUMALINK_JSON_FIELD_DECL(200)

#define LUMALINK_JSON_FIELD_SPEC_BLOCK_00 \
    LUMALINK_JSON_FIELD_SPEC(0), \
    LUMALINK_JSON_FIELD_SPEC(1), \
    LUMALINK_JSON_FIELD_SPEC(2), \
    LUMALINK_JSON_FIELD_SPEC(3), \
    LUMALINK_JSON_FIELD_SPEC(4), \
    LUMALINK_JSON_FIELD_SPEC(5), \
    LUMALINK_JSON_FIELD_SPEC(6), \
    LUMALINK_JSON_FIELD_SPEC(7), \
    LUMALINK_JSON_FIELD_SPEC(8), \
    LUMALINK_JSON_FIELD_SPEC(9),

#define LUMALINK_JSON_FIELD_SPEC_BLOCK_01 \
    LUMALINK_JSON_FIELD_SPEC(10), \
    LUMALINK_JSON_FIELD_SPEC(11), \
    LUMALINK_JSON_FIELD_SPEC(12), \
    LUMALINK_JSON_FIELD_SPEC(13), \
    LUMALINK_JSON_FIELD_SPEC(14), \
    LUMALINK_JSON_FIELD_SPEC(15), \
    LUMALINK_JSON_FIELD_SPEC(16), \
    LUMALINK_JSON_FIELD_SPEC(17), \
    LUMALINK_JSON_FIELD_SPEC(18), \
    LUMALINK_JSON_FIELD_SPEC(19),

#define LUMALINK_JSON_FIELD_SPEC_BLOCK_02 \
    LUMALINK_JSON_FIELD_SPEC(20), \
    LUMALINK_JSON_FIELD_SPEC(21), \
    LUMALINK_JSON_FIELD_SPEC(22), \
    LUMALINK_JSON_FIELD_SPEC(23), \
    LUMALINK_JSON_FIELD_SPEC(24), \
    LUMALINK_JSON_FIELD_SPEC(25), \
    LUMALINK_JSON_FIELD_SPEC(26), \
    LUMALINK_JSON_FIELD_SPEC(27), \
    LUMALINK_JSON_FIELD_SPEC(28), \
    LUMALINK_JSON_FIELD_SPEC(29),

#define LUMALINK_JSON_FIELD_SPEC_BLOCK_03 \
    LUMALINK_JSON_FIELD_SPEC(30), \
    LUMALINK_JSON_FIELD_SPEC(31), \
    LUMALINK_JSON_FIELD_SPEC(32), \
    LUMALINK_JSON_FIELD_SPEC(33), \
    LUMALINK_JSON_FIELD_SPEC(34), \
    LUMALINK_JSON_FIELD_SPEC(35), \
    LUMALINK_JSON_FIELD_SPEC(36), \
    LUMALINK_JSON_FIELD_SPEC(37), \
    LUMALINK_JSON_FIELD_SPEC(38), \
    LUMALINK_JSON_FIELD_SPEC(39),

#define LUMALINK_JSON_FIELD_SPEC_BLOCK_04 \
    LUMALINK_JSON_FIELD_SPEC(40), \
    LUMALINK_JSON_FIELD_SPEC(41), \
    LUMALINK_JSON_FIELD_SPEC(42), \
    LUMALINK_JSON_FIELD_SPEC(43), \
    LUMALINK_JSON_FIELD_SPEC(44), \
    LUMALINK_JSON_FIELD_SPEC(45), \
    LUMALINK_JSON_FIELD_SPEC(46), \
    LUMALINK_JSON_FIELD_SPEC(47), \
    LUMALINK_JSON_FIELD_SPEC(48), \
    LUMALINK_JSON_FIELD_SPEC(49),

#define LUMALINK_JSON_FIELD_SPEC_BLOCK_05 \
    LUMALINK_JSON_FIELD_SPEC(50), \
    LUMALINK_JSON_FIELD_SPEC(51), \
    LUMALINK_JSON_FIELD_SPEC(52), \
    LUMALINK_JSON_FIELD_SPEC(53), \
    LUMALINK_JSON_FIELD_SPEC(54), \
    LUMALINK_JSON_FIELD_SPEC(55), \
    LUMALINK_JSON_FIELD_SPEC(56), \
    LUMALINK_JSON_FIELD_SPEC(57), \
    LUMALINK_JSON_FIELD_SPEC(58), \
    LUMALINK_JSON_FIELD_SPEC(59),

#define LUMALINK_JSON_FIELD_SPEC_BLOCK_06 \
    LUMALINK_JSON_FIELD_SPEC(60), \
    LUMALINK_JSON_FIELD_SPEC(61), \
    LUMALINK_JSON_FIELD_SPEC(62), \
    LUMALINK_JSON_FIELD_SPEC(63), \
    LUMALINK_JSON_FIELD_SPEC(64), \
    LUMALINK_JSON_FIELD_SPEC(65), \
    LUMALINK_JSON_FIELD_SPEC(66), \
    LUMALINK_JSON_FIELD_SPEC(67), \
    LUMALINK_JSON_FIELD_SPEC(68), \
    LUMALINK_JSON_FIELD_SPEC(69),

#define LUMALINK_JSON_FIELD_SPEC_BLOCK_07 \
    LUMALINK_JSON_FIELD_SPEC(70), \
    LUMALINK_JSON_FIELD_SPEC(71), \
    LUMALINK_JSON_FIELD_SPEC(72), \
    LUMALINK_JSON_FIELD_SPEC(73), \
    LUMALINK_JSON_FIELD_SPEC(74), \
    LUMALINK_JSON_FIELD_SPEC(75), \
    LUMALINK_JSON_FIELD_SPEC(76), \
    LUMALINK_JSON_FIELD_SPEC(77), \
    LUMALINK_JSON_FIELD_SPEC(78), \
    LUMALINK_JSON_FIELD_SPEC(79),

#define LUMALINK_JSON_FIELD_SPEC_BLOCK_08 \
    LUMALINK_JSON_FIELD_SPEC(80), \
    LUMALINK_JSON_FIELD_SPEC(81), \
    LUMALINK_JSON_FIELD_SPEC(82), \
    LUMALINK_JSON_FIELD_SPEC(83), \
    LUMALINK_JSON_FIELD_SPEC(84), \
    LUMALINK_JSON_FIELD_SPEC(85), \
    LUMALINK_JSON_FIELD_SPEC(86), \
    LUMALINK_JSON_FIELD_SPEC(87), \
    LUMALINK_JSON_FIELD_SPEC(88), \
    LUMALINK_JSON_FIELD_SPEC(89),

#define LUMALINK_JSON_FIELD_SPEC_BLOCK_09 \
    LUMALINK_JSON_FIELD_SPEC(90), \
    LUMALINK_JSON_FIELD_SPEC(91), \
    LUMALINK_JSON_FIELD_SPEC(92), \
    LUMALINK_JSON_FIELD_SPEC(93), \
    LUMALINK_JSON_FIELD_SPEC(94), \
    LUMALINK_JSON_FIELD_SPEC(95), \
    LUMALINK_JSON_FIELD_SPEC(96), \
    LUMALINK_JSON_FIELD_SPEC(97), \
    LUMALINK_JSON_FIELD_SPEC(98), \
    LUMALINK_JSON_FIELD_SPEC(99),

#define LUMALINK_JSON_FIELD_SPEC_BLOCK_10 \
    LUMALINK_JSON_FIELD_SPEC(100), \
    LUMALINK_JSON_FIELD_SPEC(101), \
    LUMALINK_JSON_FIELD_SPEC(102), \
    LUMALINK_JSON_FIELD_SPEC(103), \
    LUMALINK_JSON_FIELD_SPEC(104), \
    LUMALINK_JSON_FIELD_SPEC(105), \
    LUMALINK_JSON_FIELD_SPEC(106), \
    LUMALINK_JSON_FIELD_SPEC(107), \
    LUMALINK_JSON_FIELD_SPEC(108), \
    LUMALINK_JSON_FIELD_SPEC(109),

#define LUMALINK_JSON_FIELD_SPEC_BLOCK_11 \
    LUMALINK_JSON_FIELD_SPEC(110), \
    LUMALINK_JSON_FIELD_SPEC(111), \
    LUMALINK_JSON_FIELD_SPEC(112), \
    LUMALINK_JSON_FIELD_SPEC(113), \
    LUMALINK_JSON_FIELD_SPEC(114), \
    LUMALINK_JSON_FIELD_SPEC(115), \
    LUMALINK_JSON_FIELD_SPEC(116), \
    LUMALINK_JSON_FIELD_SPEC(117), \
    LUMALINK_JSON_FIELD_SPEC(118), \
    LUMALINK_JSON_FIELD_SPEC(119),

#define LUMALINK_JSON_FIELD_SPEC_BLOCK_12 \
    LUMALINK_JSON_FIELD_SPEC(120), \
    LUMALINK_JSON_FIELD_SPEC(121), \
    LUMALINK_JSON_FIELD_SPEC(122), \
    LUMALINK_JSON_FIELD_SPEC(123), \
    LUMALINK_JSON_FIELD_SPEC(124), \
    LUMALINK_JSON_FIELD_SPEC(125), \
    LUMALINK_JSON_FIELD_SPEC(126), \
    LUMALINK_JSON_FIELD_SPEC(127), \
    LUMALINK_JSON_FIELD_SPEC(128), \
    LUMALINK_JSON_FIELD_SPEC(129),

#define LUMALINK_JSON_FIELD_SPEC_BLOCK_13 \
    LUMALINK_JSON_FIELD_SPEC(130), \
    LUMALINK_JSON_FIELD_SPEC(131), \
    LUMALINK_JSON_FIELD_SPEC(132), \
    LUMALINK_JSON_FIELD_SPEC(133), \
    LUMALINK_JSON_FIELD_SPEC(134), \
    LUMALINK_JSON_FIELD_SPEC(135), \
    LUMALINK_JSON_FIELD_SPEC(136), \
    LUMALINK_JSON_FIELD_SPEC(137), \
    LUMALINK_JSON_FIELD_SPEC(138), \
    LUMALINK_JSON_FIELD_SPEC(139),

#define LUMALINK_JSON_FIELD_SPEC_BLOCK_14 \
    LUMALINK_JSON_FIELD_SPEC(140), \
    LUMALINK_JSON_FIELD_SPEC(141), \
    LUMALINK_JSON_FIELD_SPEC(142), \
    LUMALINK_JSON_FIELD_SPEC(143), \
    LUMALINK_JSON_FIELD_SPEC(144), \
    LUMALINK_JSON_FIELD_SPEC(145), \
    LUMALINK_JSON_FIELD_SPEC(146), \
    LUMALINK_JSON_FIELD_SPEC(147), \
    LUMALINK_JSON_FIELD_SPEC(148), \
    LUMALINK_JSON_FIELD_SPEC(149),

#define LUMALINK_JSON_FIELD_SPEC_BLOCK_15 \
    LUMALINK_JSON_FIELD_SPEC(150), \
    LUMALINK_JSON_FIELD_SPEC(151), \
    LUMALINK_JSON_FIELD_SPEC(152), \
    LUMALINK_JSON_FIELD_SPEC(153), \
    LUMALINK_JSON_FIELD_SPEC(154), \
    LUMALINK_JSON_FIELD_SPEC(155), \
    LUMALINK_JSON_FIELD_SPEC(156), \
    LUMALINK_JSON_FIELD_SPEC(157), \
    LUMALINK_JSON_FIELD_SPEC(158), \
    LUMALINK_JSON_FIELD_SPEC(159),

#define LUMALINK_JSON_FIELD_SPEC_BLOCK_16 \
    LUMALINK_JSON_FIELD_SPEC(160), \
    LUMALINK_JSON_FIELD_SPEC(161), \
    LUMALINK_JSON_FIELD_SPEC(162), \
    LUMALINK_JSON_FIELD_SPEC(163), \
    LUMALINK_JSON_FIELD_SPEC(164), \
    LUMALINK_JSON_FIELD_SPEC(165), \
    LUMALINK_JSON_FIELD_SPEC(166), \
    LUMALINK_JSON_FIELD_SPEC(167), \
    LUMALINK_JSON_FIELD_SPEC(168), \
    LUMALINK_JSON_FIELD_SPEC(169),

#define LUMALINK_JSON_FIELD_SPEC_BLOCK_17 \
    LUMALINK_JSON_FIELD_SPEC(170), \
    LUMALINK_JSON_FIELD_SPEC(171), \
    LUMALINK_JSON_FIELD_SPEC(172), \
    LUMALINK_JSON_FIELD_SPEC(173), \
    LUMALINK_JSON_FIELD_SPEC(174), \
    LUMALINK_JSON_FIELD_SPEC(175), \
    LUMALINK_JSON_FIELD_SPEC(176), \
    LUMALINK_JSON_FIELD_SPEC(177), \
    LUMALINK_JSON_FIELD_SPEC(178), \
    LUMALINK_JSON_FIELD_SPEC(179),

#define LUMALINK_JSON_FIELD_SPEC_BLOCK_18 \
    LUMALINK_JSON_FIELD_SPEC(180), \
    LUMALINK_JSON_FIELD_SPEC(181), \
    LUMALINK_JSON_FIELD_SPEC(182), \
    LUMALINK_JSON_FIELD_SPEC(183), \
    LUMALINK_JSON_FIELD_SPEC(184), \
    LUMALINK_JSON_FIELD_SPEC(185), \
    LUMALINK_JSON_FIELD_SPEC(186), \
    LUMALINK_JSON_FIELD_SPEC(187), \
    LUMALINK_JSON_FIELD_SPEC(188), \
    LUMALINK_JSON_FIELD_SPEC(189),

#define LUMALINK_JSON_FIELD_SPEC_BLOCK_19 \
    LUMALINK_JSON_FIELD_SPEC(190), \
    LUMALINK_JSON_FIELD_SPEC(191), \
    LUMALINK_JSON_FIELD_SPEC(192), \
    LUMALINK_JSON_FIELD_SPEC(193), \
    LUMALINK_JSON_FIELD_SPEC(194), \
    LUMALINK_JSON_FIELD_SPEC(195), \
    LUMALINK_JSON_FIELD_SPEC(196), \
    LUMALINK_JSON_FIELD_SPEC(197), \
    LUMALINK_JSON_FIELD_SPEC(198), \
    LUMALINK_JSON_FIELD_SPEC(199),

#define LUMALINK_JSON_FIELD_SPEC_BLOCK_20 \
    LUMALINK_JSON_FIELD_SPEC(200)

struct oversized_model {
    LUMALINK_JSON_FIELD_DECL_BLOCK_00
    LUMALINK_JSON_FIELD_DECL_BLOCK_01
    LUMALINK_JSON_FIELD_DECL_BLOCK_02
    LUMALINK_JSON_FIELD_DECL_BLOCK_03
    LUMALINK_JSON_FIELD_DECL_BLOCK_04
    LUMALINK_JSON_FIELD_DECL_BLOCK_05
    LUMALINK_JSON_FIELD_DECL_BLOCK_06
    LUMALINK_JSON_FIELD_DECL_BLOCK_07
    LUMALINK_JSON_FIELD_DECL_BLOCK_08
    LUMALINK_JSON_FIELD_DECL_BLOCK_09
    LUMALINK_JSON_FIELD_DECL_BLOCK_10
    LUMALINK_JSON_FIELD_DECL_BLOCK_11
    LUMALINK_JSON_FIELD_DECL_BLOCK_12
    LUMALINK_JSON_FIELD_DECL_BLOCK_13
    LUMALINK_JSON_FIELD_DECL_BLOCK_14
    LUMALINK_JSON_FIELD_DECL_BLOCK_15
    LUMALINK_JSON_FIELD_DECL_BLOCK_16
    LUMALINK_JSON_FIELD_DECL_BLOCK_17
    LUMALINK_JSON_FIELD_DECL_BLOCK_18
    LUMALINK_JSON_FIELD_DECL_BLOCK_19
    LUMALINK_JSON_FIELD_DECL_BLOCK_20
};

using oversized_spec = lumalink::json::spec::object<
    LUMALINK_JSON_FIELD_SPEC_BLOCK_00
    LUMALINK_JSON_FIELD_SPEC_BLOCK_01
    LUMALINK_JSON_FIELD_SPEC_BLOCK_02
    LUMALINK_JSON_FIELD_SPEC_BLOCK_03
    LUMALINK_JSON_FIELD_SPEC_BLOCK_04
    LUMALINK_JSON_FIELD_SPEC_BLOCK_05
    LUMALINK_JSON_FIELD_SPEC_BLOCK_06
    LUMALINK_JSON_FIELD_SPEC_BLOCK_07
    LUMALINK_JSON_FIELD_SPEC_BLOCK_08
    LUMALINK_JSON_FIELD_SPEC_BLOCK_09
    LUMALINK_JSON_FIELD_SPEC_BLOCK_10
    LUMALINK_JSON_FIELD_SPEC_BLOCK_11
    LUMALINK_JSON_FIELD_SPEC_BLOCK_12
    LUMALINK_JSON_FIELD_SPEC_BLOCK_13
    LUMALINK_JSON_FIELD_SPEC_BLOCK_14
    LUMALINK_JSON_FIELD_SPEC_BLOCK_15
    LUMALINK_JSON_FIELD_SPEC_BLOCK_16
    LUMALINK_JSON_FIELD_SPEC_BLOCK_17
    LUMALINK_JSON_FIELD_SPEC_BLOCK_18
    LUMALINK_JSON_FIELD_SPEC_BLOCK_19
    LUMALINK_JSON_FIELD_SPEC_BLOCK_20>;

#undef LUMALINK_JSON_FIELD_DECL
#undef LUMALINK_JSON_FIELD_SPEC
#undef LUMALINK_JSON_FIELD_DECL_BLOCK_00
#undef LUMALINK_JSON_FIELD_DECL_BLOCK_01
#undef LUMALINK_JSON_FIELD_DECL_BLOCK_02
#undef LUMALINK_JSON_FIELD_DECL_BLOCK_03
#undef LUMALINK_JSON_FIELD_DECL_BLOCK_04
#undef LUMALINK_JSON_FIELD_DECL_BLOCK_05
#undef LUMALINK_JSON_FIELD_DECL_BLOCK_06
#undef LUMALINK_JSON_FIELD_DECL_BLOCK_07
#undef LUMALINK_JSON_FIELD_DECL_BLOCK_08
#undef LUMALINK_JSON_FIELD_DECL_BLOCK_09
#undef LUMALINK_JSON_FIELD_DECL_BLOCK_10
#undef LUMALINK_JSON_FIELD_DECL_BLOCK_11
#undef LUMALINK_JSON_FIELD_DECL_BLOCK_12
#undef LUMALINK_JSON_FIELD_DECL_BLOCK_13
#undef LUMALINK_JSON_FIELD_DECL_BLOCK_14
#undef LUMALINK_JSON_FIELD_DECL_BLOCK_15
#undef LUMALINK_JSON_FIELD_DECL_BLOCK_16
#undef LUMALINK_JSON_FIELD_DECL_BLOCK_17
#undef LUMALINK_JSON_FIELD_DECL_BLOCK_18
#undef LUMALINK_JSON_FIELD_DECL_BLOCK_19
#undef LUMALINK_JSON_FIELD_DECL_BLOCK_20
#undef LUMALINK_JSON_FIELD_SPEC_BLOCK_00
#undef LUMALINK_JSON_FIELD_SPEC_BLOCK_01
#undef LUMALINK_JSON_FIELD_SPEC_BLOCK_02
#undef LUMALINK_JSON_FIELD_SPEC_BLOCK_03
#undef LUMALINK_JSON_FIELD_SPEC_BLOCK_04
#undef LUMALINK_JSON_FIELD_SPEC_BLOCK_05
#undef LUMALINK_JSON_FIELD_SPEC_BLOCK_06
#undef LUMALINK_JSON_FIELD_SPEC_BLOCK_07
#undef LUMALINK_JSON_FIELD_SPEC_BLOCK_08
#undef LUMALINK_JSON_FIELD_SPEC_BLOCK_09
#undef LUMALINK_JSON_FIELD_SPEC_BLOCK_10
#undef LUMALINK_JSON_FIELD_SPEC_BLOCK_11
#undef LUMALINK_JSON_FIELD_SPEC_BLOCK_12
#undef LUMALINK_JSON_FIELD_SPEC_BLOCK_13
#undef LUMALINK_JSON_FIELD_SPEC_BLOCK_14
#undef LUMALINK_JSON_FIELD_SPEC_BLOCK_15
#undef LUMALINK_JSON_FIELD_SPEC_BLOCK_16
#undef LUMALINK_JSON_FIELD_SPEC_BLOCK_17
#undef LUMALINK_JSON_FIELD_SPEC_BLOCK_18
#undef LUMALINK_JSON_FIELD_SPEC_BLOCK_19
#undef LUMALINK_JSON_FIELD_SPEC_BLOCK_20

} // namespace

auto trigger_arity_limit_failure() {
    JsonDocument document;
    return lumalink::json::deserialize<oversized_model, oversized_spec>(document.as<JsonVariantConst>());
}